### PR TITLE
Cleanup Mod class and Proxies, Move Recipes to Java

### PR DESCRIPTION
**Pull request by serenibyss**
The title pretty much says it all, this PR cleans up the main mod class and pushes a lot to proxies, and moves json recipes into Java code. There are some weird things going on with the Upgrades, but I did not change any recipes for this PR.

### CODE REVIEW

**Comment by Zenthae** [comment]
why would you move recipes to Java when it make it harder to modify them later ?

**Comment by Exaxxion** [comment]
> why would you move recipes to Java when it make it harder to modify them later ?

In what way would it be harder to modify the recipes later by making this change? I can't think of a reason why that would be the case.

**Review by ALongStringOfNumbers — APPROVED** [review]
This looks good to me.

**Review by Exaxxion — APPROVED** [review]
Agreed, looks good to me. Didn't run into any issues testing in the dev environment and throwing the jar in an Omni snapshot.

**Pull request merged**
